### ISSUE TITLE
Feature request: option to dump file to server

### ISSUE THREAD

**Issue by scooterx3** [osalabs/phpminiadmin#25]
It would be handy I think if an option were available to dump the .sql file right onto the server rather than downloading it to the desktop machine.

**Comment by osalabs** [comment]
Thank you for feature idea. Do you have a particular need on your servers? Could you describe some realistic use case?
I am just trying to figure out if it's a really important feature to include in this small script.

**Comment by scooterx3** [comment]
Thanks for your reply. I personally use it for a website migration service.
My ideal work flow is to dump the database using SSH and leave it with the
files to be migrated, then use rsync or to copy everything over to the new
server in one go. If I don't have access to SSH and mysqldump, I rely on
phpMiniAdmin to download the sql file and then upload it to the server. But
then I have to download the sql file to the desktop and then upload to the
new server. If I could dump the sql file to the server, I could get around
needing extra steps, and avoiding potential connection speed and bandwidth
issues that may apply to the local workstation by transferring the sql file
along with the website files, directly from one server to another.
On Jun 30, 2016 7:31 PM, "Oleg Savchuk" <notifications@github.com> wrote:

Thank you for feature idea. Do you have a particular need on your servers?
Could you describe some realistic use case?
I am just trying to figure out if it's a really important feature to
include in this small script.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/osalabs/phpminiadmin/issues/25#issuecomment-229832756>,
or mute the thread
<https://github.com/notifications/unsubscribe/ACHd2OhbdYWzJ7rZPcKvsqvX217q7SN5ks5qRG3dgaJpZM4JCXJZ>
.

**Comment by osalabs** [comment]
Good work flow description, seems reasonable. 
And that would mean that import should also have an option to import from file on server, not just upload.
I'll implement necessary changes.

**Comment by scooterx3** [comment]
Yes, import from file on server would be a good idea too. Thanks!

**Comment by bennigraf** [comment]
+1, as it helps work around problems with max_upload_file_size on some hosts/hosters... :-)

**Comment by osalabs** [comment]
export and import to/from server-side file implemented
