### ISSUE TITLE
CEMI Vulnerability

### ISSUE THREAD

**Issue by ProDigySML** [osalabs/phpminiadmin#27]
PHPMiniAdmin is vulnerable to a Microsoft Excel specific attack named CSV Excel Macro Injection. An attacker can add in formulas like `=1+1` into the DB and when exported into CSV, these formulas can be executed. This can lead to the take over of a user's PC, assuming they enable macros within Microsoft Excel. 

To patch this bug, I would suggest when creating the CSV file, simply add a single quote (') before any field that contains an =, +, - or @ sign at the start of the field. 

Hope this helps keep your software more secure!

**Comment by osalabs** [comment]
well, it's actually not a phpMiniAdmin vulnerability, it's up to Excel how to import csv.
However I agree, better to add quoting

**Comment by ProDigySML** [comment]
Yeah definitely agree with that! Microsoft should really fix that up, but they are being stubborn about it. But yeah when it comes to keep users safe, sometimes the vendor has to take the initiative to make sure dependencies don't affect the software too. Glad you plan on fixing it though!

**Comment by osalabs** [comment]
After some thinking and research I've decided not to implement adding single quote as this way we actually modifying the data, which usually expected to be "as is".
Also, Excel has a warning in case you want to import something dangerous.

btw, Google also decided not to "fix" this:
https://sites.google.com/site/bughunteruniversity/nonvuln/csv-excel-formula-injection

**Comment by ProDigySML** [comment]
Fair enough. :)
