### ISSUE TITLE
Any php extension-package needed?

### ISSUE THREAD

**Issue by bendqh** [osalabs/phpminiadmin#34]
Hi,

I normally use latest Debian for new server environments on which I normally install Drupal applications.
I remember that on some new server environments, I had to install `mbstring` and `mcrypt` to use PHPMyAdmin.

I read [phpminiadmin's project page](http://phpminiadmin.sourceforge.net/) but didn't find a statement if any packages are needed (I assume none are needed).
I would personally love to read a sentence like "no php extension-packages are needed on Linux distributions/Debian".

Ben,

**Comment by stphnduvall** [comment]
none are needed

**Comment by osalabs** [comment]
Sorry for late answer. Actually `mysqli` extension is required. And I found it might not be installed by default in recent Linux/Debian distos.
Added to project description.
