### ISSUE TITLE
I get a white screen on localhost/phpminiadmin.php

### ISSUE THREAD

**Issue by onlycparra** [osalabs/phpminiadmin#36]
I cannot load phpminiadmin.php, I see an empty page, however, I am able to load another php file (phpinfo.php, containing the phpinfo() function), what else do I need to get it to work?

**Comment by onlycparra** [comment]
solved in ubuntu:
`sudo apt install php-mysql`
`sudo systemctl restart apache2.service`
reload `localhost/phpminiadmin.php`

**Comment by osalabs** [comment]
Thank you, I'll add "php-mysql" requirement to project dependencies, since it seems it's not installed by default these days.
