### ISSUE TITLE
Connecting to server via SSL

### ISSUE THREAD

**Issue by anoopjohn** [osalabs/phpminiadmin#37]
Is there some way to configure connecting to the server via SSL using ca-certs?

**Comment by osalabs** [comment]
not yet, but thank you for the request. I will need to rewrite connection code a bit.

**Comment by anoopjohn** [comment]
Will be happy to help this part working.

**Comment by osalabs** [comment]
Done. Now it's possible to define paths to ssl certificates in the `$DBDEF` config.
Define at least `$DBDEF['ssl_ca']` - that would trigger establishing SSL connection.
