### ISSUE TITLE
get_magic_quotes_gpc deprecated

### ISSUE THREAD

**Issue by jcoonrod** [osalabs/phpminiadmin#40]
Running under php 7.4 generates this warning. Apparently it should simply be removed and not replaced with anything.

**Comment by usrjense** [comment]
When updating from PHP 7.4 to 8.0 it stopped working completely

`PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /phpminiadmin.php on line 55`

**Comment by osalabs** [comment]
`get_magic_quotes_gpc` usage removed.

For those who need to use phpminiadmin with older PHP versions - just ensure to turn off magic quotes in your PHP config.
