### ISSUE TITLE
How to setup phpminiadmin

### ISSUE THREAD

**Issue by juzerali** [osalabs/phpminiadmin#7]
A mini tutorial on how to setup would be appreciated. Can you include a set up guide in Readme.md

Currently I am unable to get past the security page. I receive a blank page at http://localhost/phpminiadmin.php, I do get the page which asks for $ACCESS_PWD though. But I am unable to go to the main page despite giving correct password.

**Comment by Fadillahzakiyah** [comment]
How install phpminiadmin on windows?

**Comment by osalabs** [comment]
to install phpminiadmin - just copy it under your website directory, regardless it's under Windows or Linux or something else.
