### ISSUE TITLE
logout link

### ISSUE THREAD

**Issue by jeekajoo** [osalabs/phpminiadmin#9]
I'm using phpMiniAdmin 1.8.120514. I think a logoff link is missing in the top bar.
Can you add a link like the one you have on phpminiadmin.sourceforge.net/phpminiadmin.php :
http://phpminiadmin.sourceforge.net/phpminiadmin.php?XSS=E1b09B3c908cb&logoff=1
?

Thanks

**Comment by dinoel** [comment]
But if "remember me" checkbox is checked then there is no way to log off. (only clear browser cookies, but it's not really an option)
